# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'delete_detail_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Biztosan törli?")
        Dialog.resize(400, 257)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        Dialog.setStyleSheet("QDialog {background-color:rgb(248,245,244);} ")
        self.buttonBox.setGeometry(QtCore.QRect(30, 180, 341, 40))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel | QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("Igen")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(50, 90, 311, 20))
        #self.label.setStyleSheet("QLabel {font-weight:600;}")
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")

        #self.buttonBox.button(QtWidgets.QDialogButtonBox.Cancel).clicked.connect(self.click_cancel_button)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.button(QtWidgets.QDialogButtonBox.Cancel).setStyleSheet("QPushButton {color: #a86777; font-weight:600; background-color: #ffffff; border: 3px solid #a86777; border-radius:20px;} QPushButton:hover{color: #ffffff; background-color: #a86777;} ")
        self.buttonBox.button(QtWidgets.QDialogButtonBox.Cancel).setMinimumSize(100,40)
        self.buttonBox.button(QtWidgets.QDialogButtonBox.Ok).setStyleSheet("QPushButton {color: #a86777; font-weight:600; background-color: #ffffff; border: 3px solid #a86777; border-radius:20px;} QPushButton:hover{color: #ffffff; background-color: #a86777;} ")
        self.buttonBox.button(QtWidgets.QDialogButtonBox.Ok).setMinimumSize(100, 40)
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore

        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Törlés megerősítése"))
        self.label.setText(_translate("Dialog", "Biztosan törölni akarja a kiválasztott hirdetést?"))
        self.buttonBox.button(QtWidgets.QDialogButtonBox.Cancel).setText(_translate("Dialog","Mégse"))
        self.buttonBox.button(QtWidgets.QDialogButtonBox.Ok).setText(_translate("Dialog","Igen"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
